[package]
name = "fff-live-tracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ratatui = "0.25"
reqwest = { version = "0.11", features = ["blocking"] }
#rss = "2.0"
atom_syndication = "0.12"