[package]
name = "fff-live-tracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ratatui = "0.25"
reqwest = "0.11"
tokio = { version = "1.35", features = ["rt", "rt-multi-thread", "macros"] }